version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    # Make postgres logs. More information about logging, see official documentation: https://www.postgresql.org/docs/11/runtime-config-logging.html
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    environment:
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: "10k"
        max-file: "5"
